### PR TITLE
fix: Update .gitignore and workflows, fix camera compilation and README

### PR DESCRIPTION
**Pull request by ramazansancar**
fix: Update .gitignore and workflows, fix camera compilation and README
upd: Update variable names for consistency
upd: Update .gitignore
upg: Upgrade devDependencies packages

### CODE REVIEW

**Comment by AidanWelch** [comment]
Thank you for taking the time to open a pull request, unfortunately I'm busy right now but will get to it as soon as possible!

**Comment by ramazansancar** [comment]
Can you check? @AidanWelch

**Comment by AidanWelch** [comment]
@ramazansancar Yeah, sorry, I'll try hopefully this weekend or earlier- I've been unfortunately very busy lately.

**Comment by AidanWelch** [comment]
It is great that you fixed the Alabama script!  Thank you!  I appreciate the effort to improve the code quality, but for a lot of the older scripts, updating the variable names only has the effect of the linter yelling out you less.  It doesn't improve the quality of the code, and actually makes it easier to ignore the glaring issues with it because the linter isn't whining about it.  So, for now I won't be merging those changes.  Also, thank you for bumping the versions of packages!

**Comment by ramazansancar** [comment]
> It is great that you fixed the Alabama script! Thank you! I appreciate the effort to improve the code quality, but for a lot of the older scripts, updating the variable names only has the effect of the linter yelling out you less. It doesn't improve the quality of the code, and actually makes it easier to ignore the glaring issues with it because the linter isn't whining about it. So, for now I won't be merging those changes. Also, thank you for bumping the versions of packages!

It would have been nice because it made it easier to read. Thanks

**Comment by AidanWelch** [comment]
I understand, but I think the readability needs to be improved when those scripts are rewritten, but as of now they're deprecated

**Comment by ramazansancar** [comment]
Thanks for PR merge @AidanWelch

**Pull request merged**
